[config]
schemaVersion = "0.0.1"

[package]
namespace = "bo0tzz"
name = "PeglinTweaks"
versionNumber = "1.7.1"
description = "Various configurable tweaks to the game's behaviour and physics"
websiteUrl = "https://github.com/bo0tzz/PeglinTweaks"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1901"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []
